@startsalt directory
' title  React サンプルプロジェクト ディレクトリ構成
{
  {T
    + src
    ++ <color:#00A1FF>**app** | アプリケーションを構成するトップレベルのソースコード
    +++ App.tsx
    ++ <color:#00A1FF>**components** | React のコンポーネント
    +++ atoms
    +++ molecules
    +++ organisms
    +++ pages
    +++ templates
    ++ <color:#00A1FF>**config** | アプリケーションの設定
    ++ <color:#00A1FF>**core** | React コンポーネント以外のビジネスロジックを含むソースコード
    +++ gateways | 外部リソースとの接続用モジュール
    ++ <color:#00A1FF>**features** | ロジックと関連するコンポーネント
    ++ <color:#00A1FF>**routers** | ルーター
    ++ <color:#00A1FF>**store** | React のストア
    ++ stories | Storybook 関連ファイル
    ++ index.tsx | React エントリーポイント
  }
}
@endsalt

@startuml dependencies
' title  React サンプルプロジェクト 依存関係図
skinparam shadowing false
scale 0.8
' scale 400 width

skinparam packageStyle Rectangle

rectangle config

note top of config
  設定値
end note

rectangle index
rectangle App
rectangle routers

note top of components
  UI 部品
end note

note top of core
  UI 以外の部品
end note

package components {
  rectangle pages
  rectangle organisms
  rectangle molecules
  rectangle atoms
  rectangle templates
}

rectangle store

package features {
  rectangle slice...
}

note bottom of features
  ビジネスロジック関連の部品
  Action、Reducer、React コンポーネントも含む
end note

package core {
  rectangle gateways
}

index -> App
App --> routers
routers --> features
pages --> templates
organisms --> molecules
molecules --> atoms
templates --> organisms

store --> features

features --> components
features --> core
index --> store

features --> config
core --> config

@enduml
