@startuml directory
skinparam roundcorner 5
scale 400 width
skinparam packageStyle Rectangle
left to right direction

title React サンプルプロジェクト ディレクトリ構成

package src {
  package app {
    rectangle routers
    rectangle App.tsx
  }
  note right of app
    アプリケーションを構成する
    トップレベルのソースコード
  end note
  package core {
    rectangle gateways
    rectangle slices
    rectangle store
    rectangle usecases
  }
  note right of core
    ビジネスロジックを含めた
    ソースコード
  end note
  package ui {
    package components {
      rectangle atom
      rectangle molecules
      rectangle organisms
      rectangle pages
      rectangle templates
    }
    package controller {
    }
  }
  note right of components
    atomic design に従った分離可能な UI 部品
    ビジネスロジックを含めない
  end note
  note right of controller
    ビジネスロジックを扱う UI 部品
    ルーターから呼ばれる
  end note
}

@enduml

@startuml dependencies
scale 400 width
title  React サンプルプロジェクト 依存関係図

skinparam packageStyle Rectangle

rectangle index
rectangle App
rectangle routers
rectangle controllers
package components {
  rectangle pages
  rectangle organisms
  rectangle molecules
  rectangle atoms
  rectangle templates
}

note top of components
  UI 部品
end note

index ..> App
App ..> routers
routers ..> controllers
pages .> templates
controllers ...> pages
organisms .> molecules
molecules .> atoms
templates .> organisms

package core {
  rectangle gateways
  rectangle slices
  rectangle store
  rectangle usecases
}

controllers .> core
store .> slices
slices .> usecases
usecases .> gateways

note top of core
  ビジネスロジック
end note

@enduml
